---
defaults:
  - _self_
  - medium_model

model: Chebnet
FC_type: nonshared_uni
FK_assembled: True
FK: 8,3,8,3,8,3
n_layers:
n_channels:
n_polynomials:
M: '1'
use_bn: true
dropout: 0
bn_momentum: 0.1
