---
defaults:
  - _self_
  - hydra: predict


horizon: 1
convlayer_index: -1
path_restricted: /home/mschoett/projects/rrg-pbellec/mschoett/rs-autoregression-prediction/inputs/behavior/hcp_behavioral_RESTRICTED.csv
# passing model path is necessary for evaluation
model_path: ???

predict_variable: gender
phenotype_file: inputs/behavior/hcp_pheno.csv
fraction_sample: 0.5
random_state: 42
n_sessions: 0.25 # 0.5, 1, 2, 4
k_splits: 5
random_splits: False

# passing extracted feature path is necessary for evaluation
feature_path: ???
