---
defaults:
  - _self_
  - hydra: extract

horizon: 1
convlayer_index: -1
# passing model path is necessary for evaluation
model_folder: "/home/mschoett/projects/rrg-pbellec/mschoett/rs-autoregression-prediction/outputs/train/multiruns/2024-09-19_07-38-30_full_scaling"

sessions: 0.25
fraction: 0.2
random_state: 1