---
defaults:
  - _self_
  - hydra: predict


horizon: 1
convlayer_index: -1
# passing model path is necessary for evaluation
model_path: ???

predict_variable: gender
phenotype_file: inputs/behavior/hcp_pheno.csv
percentage_sample: 100
random_state: 42
# passing extracted feature path is necessary for evaluation
feature_path: ???
